### ISSUE TITLE
v1.5.x can't work

### ISSUE THREAD

**Issue by little-eight-china** [CanopyTax/single-spa-vue#13]
When I upgraded from 1.4.0 to 1.5.x, single-spa could not read the page. The page was blank.

**Comment by joeldenning** [comment]
Hi @little-eight-china, could you provide more details? Is there a browser console error? If so, what is it?

https://github.com/CanopyTax/single-spa-vue/pull/10 is the biggest change between 1.4.0 and 1.5.x. So any breakages might be related to that. Are you passing in an `el` option? That is what the change was related to -- you no longer have to pass in `el` if you don't want to, but if you do want to then everything should still work as it did in 1.4.0

**Comment by yordidi** [comment]
I pass an `el` option，but it always creat a new container in html。

**Comment by little-eight-china** [comment]
@joeldenning 
hi,no error in browser console, even more no error everywhere.
when i remove el option, the page still be blank.

**Comment by filoxo** [comment]
@yordidi I believe your issue is unrelated to this one. Would you mind opening a separate issue for that? Thanks!

**Comment by little-eight-china** [comment]
@joeldenning 
sorry,i can see it now .  it add the last of  the parent page，and the parent page is big, so i  thought it can't work.

**Comment by joeldenning** [comment]
@yordidi the issue you reported was tracked in #16 and is released in https://github.com/CanopyTax/single-spa-vue/releases/tag/v1.5.3

**Comment by yordidi** [comment]
@joeldenning thank you!
