### ISSUE TITLE
How to mount and unmount vuex?

### ISSUE THREAD

**Issue by ayiaq1** [CanopyTax/single-spa-vue#20]
main.js:
const vueLifecycles = singleSpaVue({
    Vue,
    appOptions: {
        el: `#modulesName`,
         store,
        render: h => h(App)
    }
});
export const bootstrap = [vueLifecycles.bootstrap];
export const mount = [vueLifecycles.mount];
export const unmount = [vueLifecycles.unmount];

I have more subjects, change subject store no destroyed

**Comment by joeldenning** [comment]
A couple options:

1. [Unsubscribe](https://vuex.vuejs.org/api/#subscribe) when `App` is unmounted.
2. [Unsubscribe](https://vuex.vuejs.org/api/#subscribe) with a custom single-spa unmount lifecycle.

I prefer Option 1. If you want to do Option 2, here's how you can:

```
js
export const unmount = [
  vueLifecycles.unmount,
  () => Promise.resolve().then(() => {
    unsubscribe()
  })
]
```

I'm closing this since I think I've answered the question, but feel free to comment further or reopen.

**Comment by fyzwjd** [comment]
> A couple options:
> 
> 1. [Unsubscribe](https://vuex.vuejs.org/api/#subscribe) when `App` is unmounted.
> 2. [Unsubscribe](https://vuex.vuejs.org/api/#subscribe) with a custom single-spa unmount lifecycle.
> 
> I prefer Option 1. If you want to do Option 2, here's how you can:
> 
> ```
> js
> export const unmount = [
>   vueLifecycles.unmount,
>   () => Promise.resolve().then(() => {
>     unsubscribe()
>   })
> ]
> ```
> 
> I'm closing this since I think I've answered the question, but feel free to comment further or reopen.

I wonder how to share store between subjects by vuex. I would be appreciate if you can share a solution.

**Comment by ayiaq1** [comment]
Intermediate values are stored through Rxjs

**Comment by fyzwjd** [comment]
> Intermediate values are stored through Rxjs

Thanks，but my apps are old projects using vuex. Switching to rxjs would be very costly. So, is any way to share store by vuex ？

**Comment by frehner** [comment]
https://single-spa.js.org/docs/faq/#how-can-i-share-application-state-between-applications

**Comment by fyzwjd** [comment]
> https://single-spa.js.org/docs/faq/#how-can-i-share-application-state-between-applications

OK, thanks for @frehner , I will try it.
