### ISSUE TITLE
Append application somewhere other than directly on document.body

### ISSUE THREAD

**Issue by brcpar** [CanopyTax/single-spa-vue#22]
If we pass in appOptions.el, we get replacement of the specified element, but there isn't currently a way to append to a specified element.
Use case: having a primary content section that you want to have apps injected into conditionally.

Consider adding something like an appOptions.appendEl that takes the DOM element id for the element for appending. Then adjusting the mount function to something like this:

```
...
if (!domEl) {
            domEl = document.createElement('div')
            domEl.id = htmlId
            if (appOptions.appendEl) {
              document.getElementById(appOptions.appendEl).appendChild(domEl);
            } else {
              document.body.appendChild(domEl)
            }
          }
...
```
I can create a pull request if you think this might be useful.

**Comment by frehner** [comment]
Oh interesting, it looks like vue doesn't have the `domElementGetter` option that single-spa-react (and angular too I believe?) has. 

https://single-spa.js.org/docs/ecosystem-react.html#options

https://github.com/CanopyTax/single-spa-react/blob/master/src/single-spa-react.js#L17

would be nice to add it for a similar API.

**Comment by joeldenning** [comment]
@frehner this is already possible in single-spa-vue. Code:
https://github.com/CanopyTax/single-spa-vue/blob/6dc5ad8b6e7d2d26c0f17da602e59bff7fe9aa82/src/single-spa-vue.js#L51

@brcpar you can do this by passing in `appOptions.el` in your call to `singleSpaVue()`. From the [single-spa-vue docs](https://single-spa.js.org/docs/ecosystem-vue.html#options):

> appOptions: (required) An object which will be used to instantiate your Vue.js application. appOptions will pass directly through to new Vue(appOptions). Note that if you do not provide an el to appOptions, that a div will be created and appended to the DOM as a default container for your Vue application.

The `appOptions` are passed directly into `new Vue(appOptions)`. You can read more about those options [in the official vue docs](https://vuejs.org/v2/api/#Options-DOM).

To do this, here's some example code:

```js
const vueLifecycles = singleSpaVue({
  Vue,
  appOptions: {
    render: h => h(App),
    router,
    el: "#my-custom-dom-element-container"
  },
});
```

Closing this since this is not a missing feature and I've provided info on how to do this. Feel free to comment further or reopen with more discussion

**Comment by brcpar** [comment]
@joeldenning, I don't think I explained the problem very well the first time. The problem when you use the appOptions.el is that it completely replaces that DOM element.  Assume for instance, in your demo project: [coexisting-vue-microfrontends](https://github.com/joeldenning/coexisting-vue-microfrontends) that you added this div in the index.html of the root-html-file:
`<div id="main-content"></div>`
Then for app1 and app2 you included in both's appOptions:
`el: '#main-content' `
After one of the apps is loaded, the div of id 'main-content' was replaced by whichever app was created first meaning the second will never be able to be injected.  The idea would be to have a static container in the root html to inject into instead of replace so that you can have your root html project handle a single layout with n apps loaded into a single container.

Does that make more sense?

**Comment by joeldenning** [comment]
Ah I see - I got confused.

>  Then for app1 and app2 you included in both's appOptions:
>  el: '#main-content' 

Don't do this. Each single-spa application's `el` should be unique. If you don't want the divs to be appended to document.body, do this:

```html
<body>
  <div id="all-apps">
    <div id="app1"></div>
    <div id="app2"></div>
  </div>
</body>
```

```js
// app1.js
singleSpaVue({
  appOptions: {
    el: '#app1'
  }
})
```

```js
// app1.js
singleSpaVue({
  appOptions: {
    el: '#app2'
  }
})
```

If for some reason this isn't good enough, you can try using [Vue's fully deprecated `replace` appOption](https://vuejs.org/v2/guide/migration.html#replace-false-removed). However, it was deprecated for a reason. It's best just to ensure separate containers for you applications.
