### ISSUE TITLE
What is the correct way to use Vue's router?

### ISSUE THREAD

**Issue by light24bulbs** [CanopyTax/single-spa-vue#5]
Is there some example of how to setup the vue router with single-spa?  If I use mode: 'history' it overwrites the page route breaking singlespa, and if I use the default mode which is hash based, it doesn't work at all.  Is vue router compatible with single-spa?

**Comment by joeldenning** [comment]
Apologies for the slow response here -- your normal vue router should work seamlessly with single-spa as long as the following things are met:

The vue router needs to remove event listeners for hashchange and popstate whenever the vue app is unmounted by single-spa
The vue routes need to be sub routes of the route specified in the vue app's activity function

Let me know if that helps - and feel free to reopen with further questions
