### ISSUE TITLE
Is there some example of how to setup the vue router with single-spa?

### ISSUE THREAD

**Issue by lukalulu** [CanopyTax/single-spa-vue#6]
Is there some example of how to setup the vue router with single-spa?

**Comment by egoisticum** [comment]
The best I could found is this one https://github.com/CanopyTax/single-spa/issues/228

**Comment by littleluckly** [comment]
i also want to know

**Comment by ranaAlkha-infotrack** [comment]
is needed here too

**Comment by lzm420241** [comment]
i had tried,but nothing can i work! it doesn't friendly for vue.

**Comment by joeldenning** [comment]
I'll be  working on this soon. Priorities for me are to finish single-spa-angular@3 and then switch to building a vue-cli plugin for single-spa and iron out any router support issues.

**Comment by little-eight-china** [comment]
route-view cannot work too

**Comment by little-eight-china** [comment]
在vue-router的index.js中导入相应的页面,并修改router的base为指定的url前缀，mode为history，即可
```
// demo
import Vue from 'vue'
import Router from 'vue-router'

import index from '@/components/index.vue'

Vue.use(Router)

export default new Router({
  base: "/#/app2/",
  mode: 'history',
  routes: [
     {
      path: '/',
      component: resolve => require(['@/components/index'], resolve),
    }
  ]
})
```

**Comment by snowlotus** [comment]
@little-eight-china 你好，有没有完整的例子可以参考下呢？我最近也在做这一块，首页可以正常加载，当路由跳转到vue app的其它页面时就不行了，此时加载的还是首页的内容。

**Comment by joeldenning** [comment]
The [documentation](https://single-spa.js.org/docs/ecosystem-vue.html) now includes routing.

Here's an [example repo](https://single-spa.js.org/docs/ecosystem-vue.html). And here's a [live demo](https://single-spa.js.org/docs/ecosystem-vue.html)

**Comment by SuperMohit** [comment]
I am trying this with Vue3 but it seems RouterView doesn't work.

**Comment by ricky2k7** [comment]
Also having issues with Vue 3 and RouterView 😢

**Comment by SuperMohit** [comment]
> Also having issues with Vue 3 and RouterView 😢

@ricky2k7  Worked for me with Webpack. Also, RouterView should be enclosed in a div. 
Are you using Vite?

**Comment by ricky2k7** [comment]
@SuperMohit We are using Vite, Webpack isn't an option for us.
